// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function StartBackupPreparation(arg1) {
  return window['go']['main']['App']['StartBackupPreparation'](arg1);
}

export function StartIncrementalBackup(arg1, arg2) {
  return window['go']['main']['App']['StartIncrementalBackup'](arg1, arg2);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function ValidateWorkspace(arg1) {
  return window['go']['main']['App']['ValidateWorkspace'](arg1);
}
