// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {task_manager} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GeneratePassword():Promise<string>;

export function ScanWorkspace(arg1:string):Promise<Array<types.TreeNode>>;

export function SelectDirectory():Promise<string>;

export function StartBackupExecution(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<task_manager.BackupResult>;

export function StartBackupPreparation(arg1:string,arg2:number,arg3:number):Promise<Array<types.Episode>>;
