// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GeneratePassword() {
  return window['go']['main']['App']['GeneratePassword']();
}

export function ScanWorkspace(arg1) {
  return window['go']['main']['App']['ScanWorkspace'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartBackupExecution(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartBackupExecution'](arg1, arg2, arg3, arg4, arg5);
}

export function StartBackupPreparation(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartBackupPreparation'](arg1, arg2, arg3);
}
