// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetTaskStatus():Promise<types.TaskStatus>;

export function SelectWorkspace():Promise<string>;

export function StartBackupPreparation(arg1:string):Promise<types.BackupPreparationResult>;

export function StartIncrementalBackup(arg1:string,arg2:string):Promise<void>;

export function StopTask():Promise<void>;

export function ValidateWorkspace(arg1:string):Promise<void>;
